name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Lightsail Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: bitnami
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/bitnami/wicys-at-osu
            git pull https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/jamie-dang-n/wicys-at-osu.git main
            npm install
            pm2 restart server.js

