name: Deploy to Lightsail
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to Lightsail Instance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Add host key to known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      
      - name: Deploy to server
        run: |
          ssh bitnami@${{ secrets.SSH_HOST }} "cd /home/bitnami/wicys-at-osu && \
          git pull https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/jamie-dang-n/wicys-at-osu.git main && \
          npm install && \
          pm2 restart server.js"
