name: Deploy to Lightsail

on:
  push:
    branches:
      - main

    jobs:
      deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: SSH into server and deploy
            uses: appleboy/ssh-action@v0.1.6
            with:
              host: ${{ secrets.SSH_HOST }}
              username: ubuntu
              key: ${{ secrets.SSH_PRIVATE_KEY }}
              script: |
                cd /wicys-at-osu
                git pull origin main
                npm install
                pm2 restart app.js

